# Generated by Django 3.1 on 2021-03-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='recipe',
            new_name='product',
        ),
    ]
