# Generated by Django 3.1 on 2021-03-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210305_0747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
